export default {
    REQUESTING: 'REQUESTING',
    FINISHED_REQUEST: 'FINISHED_REQUEST',
    UPDATE_TAB_BOTTOM:'UPDATE_TAB_BOTTOM',
    //user
    
    SUCCESS_GETLIST_USER:'SUCCESS_GETLIST_USER',
    FAILD_GETLIST_USER:'FAILD_GETLIST_USER',
    SUCCESS_GET_USER:'SUCCESS_GET_USER',
    FAILD_GET_USER:'FAILD_GET_USER',


}